"""datos escolares del alumno

Revision ID: 3ca9a1b0c73e
Revises: a2656ed856c3
Create Date: 2026-08-23 15:19:40.834186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca9a1b0c73e'
down_revision: Union[str, None] = 'a2656ed856c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_escolares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('nombre_pila', sa.String(length=100), nullable=False),
    sa.Column('lugar_nacimiento', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('estado_civil', sa.String(length=30), nullable=False),
    sa.Column('discapacidad', sa.String(length=50), nullable=False),
    sa.Column('domicilio', sa.String(length=200), nullable=False),
    sa.Column('colonia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('entidad_federativa', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo_personal', sa.String(length=200), nullable=False),
    sa.Column('grado_academico', sa.String(length=50), nullable=False),
    sa.Column('promedio_semestre_anterior', sa.Float(), nullable=False),
    sa.Column('becado_por', sa.String(length=100), nullable=True),
    sa.Column('materias_examen_especial', sa.String(length=200), nullable=True),
    sa.Column('ingreso_mensual', sa.Float(), nullable=False),
    sa.Column('integrantes_hogar', sa.Integer(), nullable=False),
    sa.Column('grupo_etnico', sa.Boolean(), nullable=False),
    sa.Column('riesgo_abandono', sa.String(length=50), nullable=False),
    sa.Column('nombre_padre', sa.String(length=200), nullable=True),
    sa.Column('domicilio_padre', sa.String(length=200), nullable=True),
    sa.Column('colonia_padre', sa.String(length=100), nullable=True),
    sa.Column('ciudad_padre', sa.String(length=100), nullable=True),
    sa.Column('entidad_padre', sa.String(length=100), nullable=True),
    sa.Column('telefono_padre', sa.String(length=30), nullable=True),
    sa.Column('nombre_madre', sa.String(length=200), nullable=True),
    sa.Column('domicilio_madre', sa.String(length=200), nullable=True),
    sa.Column('colonia_madre', sa.String(length=100), nullable=True),
    sa.Column('ciudad_madre', sa.String(length=100), nullable=True),
    sa.Column('entidad_madre', sa.String(length=100), nullable=True),
    sa.Column('telefono_madre', sa.String(length=30), nullable=True),
    sa.Column('empresa_nombre', sa.String(length=200), nullable=True),
    sa.Column('empresa_domicilio', sa.String(length=200), nullable=True),
    sa.Column('empresa_colonia', sa.String(length=100), nullable=True),
    sa.Column('empresa_ciudad', sa.String(length=100), nullable=True),
    sa.Column('empresa_entidad', sa.String(length=100), nullable=True),
    sa.Column('empresa_telefono', sa.String(length=30), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('antiguedad', sa.String(length=50), nullable=True),
    sa.Column('jefe_inmediato', sa.String(length=200), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos_escolares')
    # ### end Alembic commands ###
