"""curp, beca pronabes, estatus de reinscripcion

Revision ID: 56a9296bb464
Revises: 6828c7236b51
Create Date: 2026-08-23 14:20:28.648668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a9296bb464'
down_revision: Union[str, None] = '6828c7236b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estatus_reinscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.String(length=20), nullable=True),
    sa.Column('mensaje_adicional', sa.String(length=200), nullable=True),
    sa.Column('autorizado', sa.Boolean(), nullable=False),
    sa.Column('adeudo_biblioteca', sa.Boolean(), nullable=False),
    sa.Column('adeudo_escolares', sa.Boolean(), nullable=False),
    sa.Column('adeudo_financieros', sa.Boolean(), nullable=False),
    sa.Column('adeudo_encuesta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alumnos', sa.Column('curp', sa.String(length=20), nullable=False))
    op.add_column('alumnos', sa.Column('beca_pronabes', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'beca_pronabes')
    op.drop_column('alumnos', 'curp')
    op.drop_table('estatus_reinscripcion')
    # ### end Alembic commands ###
