"""fase 2: campos reales de alumno, unidades en calificaciones, avance reticular

Revision ID: 6828c7236b51
Revises: 77e250fb3746
Create Date: 2026-08-23 14:04:35.405136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6828c7236b51'
down_revision: Union[str, None] = '77e250fb3746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avance_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('semestre_curricular', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('calificacion_display', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alumnos', sa.Column('plan_estudios', sa.String(length=50), nullable=False))
    op.add_column('alumnos', sa.Column('reticula', sa.Integer(), nullable=False))
    op.add_column('alumnos', sa.Column('especialidad', sa.String(length=200), nullable=False))
    op.add_column('alumnos', sa.Column('promedio_certificado', sa.Float(), nullable=False))
    op.add_column('calificaciones', sa.Column('unidades', sa.JSON(), nullable=False))
    op.add_column('calificaciones', sa.Column('evaluacion', sa.String(length=30), nullable=True))
    op.add_column('calificaciones', sa.Column('observaciones', sa.String(length=100), nullable=True))
    op.drop_column('calificaciones', 'parcial3')
    op.drop_column('calificaciones', 'parcial1')
    op.drop_column('calificaciones', 'parcial2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificaciones', sa.Column('parcial2', sa.FLOAT(), nullable=True))
    op.add_column('calificaciones', sa.Column('parcial1', sa.FLOAT(), nullable=True))
    op.add_column('calificaciones', sa.Column('parcial3', sa.FLOAT(), nullable=True))
    op.drop_column('calificaciones', 'observaciones')
    op.drop_column('calificaciones', 'evaluacion')
    op.drop_column('calificaciones', 'unidades')
    op.drop_column('alumnos', 'promedio_certificado')
    op.drop_column('alumnos', 'especialidad')
    op.drop_column('alumnos', 'reticula')
    op.drop_column('alumnos', 'plan_estudios')
    op.drop_table('avance_materias')
    # ### end Alembic commands ###
