"""semestre en grupo, catalogo grupos cargados

Revision ID: 973be57e986b
Revises: 3ca9a1b0c73e
Create Date: 2026-08-23 18:38:15.342820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973be57e986b'
down_revision: Union[str, None] = '3ca9a1b0c73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos', sa.Column('semestre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grupos', 'semestre')
    # ### end Alembic commands ###
