"""residencias y fichas de pago

Revision ID: a2656ed856c3
Revises: 56a9296bb464
Create Date: 2026-08-23 14:39:03.877024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2656ed856c3'
down_revision: Union[str, None] = '56a9296bb464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fichas_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('referencia_bancaria', sa.String(length=50), nullable=False),
    sa.Column('fecha_vencimiento', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=False),
    sa.Column('puesto', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=20), nullable=False),
    sa.Column('fecha_fin', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residencias')
    op.drop_table('fichas_pago')
    # ### end Alembic commands ###
